//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT_EMP
    {
        public System.DateTime FECHA { get; set; }
        public string EFECTUADA { get; set; }
        public string EMPRESA_EMP_RUT { get; set; }
        public decimal ACTIV_PREVENTIVA_ACTI_ID { get; set; }
    
        public virtual ACTIV_PREVENTIVA ACTIV_PREVENTIVA { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
