//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class CANT_SERVICIO
    {
        public decimal CANT_SERVICIO1 { get; set; }
        public decimal CANT_VALOR { get; set; }
        public System.DateTime CANT_FECHA { get; set; }
        public decimal CONTRATO_CONTRATO_ID { get; set; }
        public decimal SERVICIO_SER_ID { get; set; }
    
        public virtual CONTRATO CONTRATO { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
