//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAPACITACION
    {
        public CAPACITACION()
        {
            this.DETALLE = new HashSet<DETALLE>();
        }
    
        public decimal CAPAC_ID { get; set; }
        public System.DateTime CAPAC_HORA { get; set; }
        public string CAPAC_TIPO { get; set; }
        public string CAPAC_DETALLE { get; set; }
        public System.DateTime CAP_FECH { get; set; }
        public decimal CAPAC_NUM { get; set; }
        public string EMPRESA_EMP_RUT { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual ICollection<DETALLE> DETALLE { get; set; }
    }
}
