//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public CONTRATO()
        {
            this.CANT_SERVICIO = new HashSet<CANT_SERVICIO>();
        }
    
        public decimal CONTRATO_ID { get; set; }
        public System.DateTime CONTRATO_FECINI { get; set; }
        public System.DateTime CONTRATO_FECTERMINO { get; set; }
        public string CONTRATO_ACTIVO { get; set; }
        public string EMPRESA_EMP_RUT { get; set; }
    
        public virtual ICollection<CANT_SERVICIO> CANT_SERVICIO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
