//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE
    {
        public decimal DETALLE_CANT { get; set; }
        public decimal CAPACITACION_CAPAC_ID { get; set; }
        public decimal MATERIAL_MATERIAL_ID { get; set; }
    
        public virtual CAPACITACION CAPACITACION { get; set; }
        public virtual MATERIAL MATERIAL { get; set; }
    }
}
