//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALL_RUBRO
    {
        public decimal CANTIDAD_RUBRO { get; set; }
        public string EMPRESA_EMP_RUT { get; set; }
        public decimal RUBRO_RUBRO_ID { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
        public virtual RUBRO RUBRO { get; set; }
    }
}
