//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTERACCION
    {
        public decimal INTERA_ID { get; set; }
        public string INTERA_TIPO { get; set; }
        public System.DateTime INTERA_FECHA { get; set; }
        public string INTERA_DESCRIPCION { get; set; }
        public Nullable<decimal> ASESORIA_ASES_ID { get; set; }
    
        public virtual ASESORIA ASESORIA { get; set; }
    }
}
