//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_ACCIDENTE
    {
        public decimal LOG_ID { get; set; }
        public string LOG_DESCR { get; set; }
        public System.DateTime LOG_HORA { get; set; }
        public System.DateTime LOG_FECHA { get; set; }
        public Nullable<decimal> ASESORIA_ASES_ID { get; set; }
        public decimal LOG_FECHA_ALERTA_ID { get; set; }
    
        public virtual ASESORIA ASESORIA { get; set; }
        public virtual LOG_FECHA LOG_FECHA1 { get; set; }
    }
}
