//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_FIZCALI
    {
        public decimal FISCA_ID { get; set; }
        public string FISCA_DETALLE { get; set; }
        public string FISCA_DILIGENCIA { get; set; }
        public Nullable<decimal> ASESORIA_ASES_ID { get; set; }
    
        public virtual ASESORIA ASESORIA { get; set; }
    }
}
