//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_FECHA
    {
        public LOG_FECHA()
        {
            this.LOG_ACCIDENTE = new HashSet<LOG_ACCIDENTE>();
        }
    
        public decimal ALERTA_ID { get; set; }
        public string ALERTA_NOMBRE { get; set; }
    
        public virtual ICollection<LOG_ACCIDENTE> LOG_ACCIDENTE { get; set; }
    }
}
