//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIAL
    {
        public MATERIAL()
        {
            this.DETALLE = new HashSet<DETALLE>();
        }
    
        public decimal MATERIAL_ID { get; set; }
        public string MATERIAL_NOMBRE { get; set; }
    
        public virtual ICollection<DETALLE> DETALLE { get; set; }
    }
}
