//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEJORA
    {
        public MEJORA()
        {
            this.VALIDAR_MEJORA = new HashSet<VALIDAR_MEJORA>();
        }
    
        public decimal MEJORAS_ID { get; set; }
        public string MEJORAS_DETALLE { get; set; }
        public string COMPLETADO { get; set; }
        public decimal ASESORIA_ASES_ID { get; set; }
        public string PROFESIONAL_PROF_RUT { get; set; }
    
        public virtual ASESORIA ASESORIA { get; set; }
        public virtual PROFESIONAL PROFESIONAL { get; set; }
        public virtual ICollection<VALIDAR_MEJORA> VALIDAR_MEJORA { get; set; }
    }
}
