//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACT_EMP> ACT_EMP { get; set; }
        public DbSet<ACTIV_PREVENTIVA> ACTIV_PREVENTIVA { get; set; }
        public DbSet<AREAPROF> AREAPROF { get; set; }
        public DbSet<ASESORIA> ASESORIA { get; set; }
        public DbSet<CANT_SERVICIO> CANT_SERVICIO { get; set; }
        public DbSet<CAPACITACION> CAPACITACION { get; set; }
        public DbSet<CONTRATO> CONTRATO { get; set; }
        public DbSet<DETALL_RUBRO> DETALL_RUBRO { get; set; }
        public DbSet<DETALLE> DETALLE { get; set; }
        public DbSet<EMPRESA> EMPRESA { get; set; }
        public DbSet<INTERACCION> INTERACCION { get; set; }
        public DbSet<LLAMADO> LLAMADO { get; set; }
        public DbSet<LOG_ACCIDENTE> LOG_ACCIDENTE { get; set; }
        public DbSet<LOG_FECHA> LOG_FECHA { get; set; }
        public DbSet<LOG_FIZCALI> LOG_FIZCALI { get; set; }
        public DbSet<MATERIAL> MATERIAL { get; set; }
        public DbSet<MEJORA> MEJORA { get; set; }
        public DbSet<MULTA> MULTA { get; set; }
        public DbSet<PAGO_EXTRA> PAGO_EXTRA { get; set; }
        public DbSet<PAGOS> PAGOS { get; set; }
        public DbSet<PROFESIONAL> PROFESIONAL { get; set; }
        public DbSet<RUBRO> RUBRO { get; set; }
        public DbSet<SERVICIO> SERVICIO { get; set; }
        public DbSet<USUARIO_ADMIN> USUARIO_ADMIN { get; set; }
        public DbSet<USUARIOEMPRESA> USUARIOEMPRESA { get; set; }
        public DbSet<VALIDAR_MEJORA> VALIDAR_MEJORA { get; set; }
        public DbSet<VISITA> VISITA { get; set; }
    }
}
