//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class MULTA
    {
        public decimal MULTA_ID { get; set; }
        public decimal MULTA_MONTO { get; set; }
        public System.DateTime MULTA_FECHORA { get; set; }
        public string EMPRESA_EMP_RUT { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
