//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO_EXTRA
    {
        public decimal EXTRA_ID { get; set; }
        public decimal EXTRA_CANTIDAD { get; set; }
        public System.DateTime EXTRA_FECHAH { get; set; }
        public string EXTRA_DESCRIPCION { get; set; }
        public string EMPRESA_EMP_RUT { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
