//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROFESIONAL
    {
        public PROFESIONAL()
        {
            this.ACTIV_PREVENTIVA = new HashSet<ACTIV_PREVENTIVA>();
            this.LLAMADO = new HashSet<LLAMADO>();
            this.MEJORA = new HashSet<MEJORA>();
            this.VALIDAR_MEJORA = new HashSet<VALIDAR_MEJORA>();
            this.VISITA = new HashSet<VISITA>();
        }
    
        public string PROF_RUT { get; set; }
        public string PROF_NOMBRE { get; set; }
        public string PROF_APELLIDO { get; set; }
        public string PROF_ACTIVO { get; set; }
        public string PROF_CORREO { get; set; }
        public string PROF_PASS { get; set; }
        public string PROF_TELEFONO { get; set; }
        public decimal AREAPROF_AREA_ID { get; set; }
    
        public virtual ICollection<ACTIV_PREVENTIVA> ACTIV_PREVENTIVA { get; set; }
        public virtual AREAPROF AREAPROF { get; set; }
        public virtual ICollection<LLAMADO> LLAMADO { get; set; }
        public virtual ICollection<MEJORA> MEJORA { get; set; }
        public virtual ICollection<VALIDAR_MEJORA> VALIDAR_MEJORA { get; set; }
        public virtual ICollection<VISITA> VISITA { get; set; }
    }
}
