//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.CANT_SERVICIO = new HashSet<CANT_SERVICIO>();
        }
    
        public decimal SER_ID { get; set; }
        public string SER_NOMBRE { get; set; }
        public decimal SER_VALOR { get; set; }
        public string SER_ACTIVO { get; set; }
    
        public virtual ICollection<CANT_SERVICIO> CANT_SERVICIO { get; set; }
    }
}
