//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOEMPRESA
    {
        public string USER_RUT { get; set; }
        public string USER_NOMBRE { get; set; }
        public string USER_CORREO { get; set; }
        public string USER_PASS { get; set; }
        public string USER_ACTIVO { get; set; }
        public string EMPRESA_EMP_RUT { get; set; }
    
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
