//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALIDAR_MEJORA
    {
        public decimal ID_VALIDACION { get; set; }
        public string CORRECCION { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHA_VALIDA { get; set; }
        public string PROFESIONAL_PROF_RUT { get; set; }
        public decimal MEJORA_MEJORAS_ID { get; set; }
    
        public virtual MEJORA MEJORA { get; set; }
        public virtual PROFESIONAL PROFESIONAL { get; set; }
    }
}
