//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios
{
    using System;
    using System.Collections.Generic;
    
    public partial class VISITA
    {
        public decimal VISITA_ID { get; set; }
        public System.DateTime VISITA_FECHA { get; set; }
        public System.DateTime VISITA_HORA { get; set; }
        public string VISITA_DESCRIPCION { get; set; }
        public string VISITA_REALIZADA { get; set; }
        public string PROFESIONAL_PROF_RUT { get; set; }
        public decimal ASESORIA_ASES_ID { get; set; }
    
        public virtual ASESORIA ASESORIA { get; set; }
        public virtual PROFESIONAL PROFESIONAL { get; set; }
    }
}
